// This file will be auto-generated by running:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

// For now, here's a basic structure:

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          company_name: string | null
          phone: string | null
          role: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          company_name?: string | null
          phone?: string | null
          role?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          company_name?: string | null
          phone?: string | null
          role?: string
          created_at?: string
          updated_at?: string
        }
      }
      listings: {
        Row: {
          id: string
          user_id: string
          category: string
          subcategory: string | null
          equipment_type: string
          make: string | null
          model: string | null
          year: string | null
          condition: string | null
          location: string
          latitude: number | null
          longitude: number | null
          description: string | null
          photos: string[] | null
          asking_price: number | null
          status: string
          is_featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          category: string
          subcategory?: string | null
          equipment_type: string
          make?: string | null
          model?: string | null
          year?: string | null
          condition?: string | null
          location: string
          latitude?: number | null
          longitude?: number | null
          description?: string | null
          photos?: string[] | null
          asking_price?: number | null
          status?: string
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          category?: string
          subcategory?: string | null
          equipment_type?: string
          make?: string | null
          model?: string | null
          year?: string | null
          condition?: string | null
          location?: string
          latitude?: number | null
          longitude?: number | null
          description?: string | null
          photos?: string[] | null
          asking_price?: number | null
          status?: string
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      valuation_requests: {
        Row: {
          id: string
          equipment_type: string
          make: string | null
          model: string | null
          year: string | null
          condition: string | null
          location: string
          contact_name: string
          contact_email: string
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          equipment_type: string
          make?: string | null
          model?: string | null
          year?: string | null
          condition?: string | null
          location: string
          contact_name: string
          contact_email: string
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          equipment_type?: string
          make?: string | null
          model?: string | null
          year?: string | null
          condition?: string | null
          location?: string
          contact_name?: string
          contact_email?: string
          status?: string
          created_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          created_at?: string
        }
      }
      subcategories: {
        Row: {
          id: string
          category_id: string
          name: string
          slug: string
          created_at: string
        }
        Insert: {
          id?: string
          category_id: string
          name: string
          slug: string
          created_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          name?: string
          slug?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}